[I 2025-06-04 18:55:13,020] A new study created in RDB with name: gcn_Task2s_A
/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/torch/nn/modules/loss.py:933: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)
[W 2025-06-04 20:14:12,758] Trial 0 failed with parameters: {'lr': 0.004058131129049944, 'dropout': 0.2901428612819832, 'hidden_classes': 149, 'optimizer': 'adam'} because of the following error: NameError("name 'trial' is not defined").
Traceback (most recent call last):
  File "/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/sujithsaisripadam/Downloads/My_Internship-work/Graph/GCN/Audio_train.py", line 403, in objective_ADAM
    val_loss, stop_epoch = train_valid_loop_ADAM(lr, dr, hidden_classes, trial_subdir, plot_subdir, task_name, batch_size, optimizer_name)
  File "/Users/sujithsaisripadam/Downloads/My_Internship-work/Graph/GCN/Audio_train.py", line 300, in train_valid_loop_ADAM
    trail_num= trial.number
NameError: name 'trial' is not defined
[W 2025-06-04 20:14:12,760] Trial 0 failed with value None.
Device cpu
[INFO] Batch Size      : 4
[INFO] Num Trials      : 2
[INFO] Task Name (A)   : Task2s_A
[INFO] Task Name (V)   : Task_2s
n1 = 39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
n2 = 39
lenoftrials :  0
num trials 2
learning rate:0.004058131129049944,dropout: 0.2901428612819832, hidden_classes: 149, optimizer: adam
Training for test subject 0 - Task2s_A
Training for test subject 1 - Task2s_A
Training for test subject 2 - Task2s_A
Training for test subject 3 - Task2s_A
Training for test subject 4 - Task2s_A
Training for test subject 5 - Task2s_A
Training for test subject 6 - Task2s_A
Training for test subject 7 - Task2s_A
Training for test subject 8 - Task2s_A
Training for test subject 9 - Task2s_A
Training for test subject 10 - Task2s_A
Training for test subject 11 - Task2s_A
Training for test subject 12 - Task2s_A
Training for test subject 13 - Task2s_A
Training for test subject 14 - Task2s_A
Training for test subject 15 - Task2s_A
Training for test subject 16 - Task2s_A
Training for test subject 17 - Task2s_A
Training for test subject 18 - Task2s_A
Training for test subject 19 - Task2s_A
Training for test subject 20 - Task2s_A
Training for test subject 21 - Task2s_A
Training for test subject 22 - Task2s_A
Training for test subject 23 - Task2s_A
Training for test subject 24 - Task2s_A
Training for test subject 25 - Task2s_A
Training for test subject 26 - Task2s_A
Training for test subject 27 - Task2s_A
Training for test subject 28 - Task2s_A
Training for test subject 29 - Task2s_A
Training for test subject 30 - Task2s_A
Training for test subject 31 - Task2s_A
Training for test subject 32 - Task2s_A
Training for test subject 33 - Task2s_A
Training for test subject 34 - Task2s_A
Training for test subject 35 - Task2s_A
Training for test subject 36 - Task2s_A
Training for test subject 37 - Task2s_A
Training for test subject 38 - Task2s_A
Final validation loss: 3.651381276680555e-05
Total predictions collected: 39
Traceback (most recent call last):
  File "/Users/sujithsaisripadam/Downloads/My_Internship-work/Graph/GCN/Audio_train.py", line 448, in <module>
    study.optimize(objective_ADAM, n_trials=num_trials_remaining)
  File "/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/opt/anaconda3/envs/graph_camb/lib/python3.10/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/sujithsaisripadam/Downloads/My_Internship-work/Graph/GCN/Audio_train.py", line 403, in objective_ADAM
    val_loss, stop_epoch = train_valid_loop_ADAM(lr, dr, hidden_classes, trial_subdir, plot_subdir, task_name, batch_size, optimizer_name)
  File "/Users/sujithsaisripadam/Downloads/My_Internship-work/Graph/GCN/Audio_train.py", line 300, in train_valid_loop_ADAM
    trail_num= trial.number
NameError: name 'trial' is not defined
